# Generated by Django 6.0.2 on 2026-02-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='resume_analysis',
            new_name='ResumeAnalysis',
        ),
    ]
