# Generated by Django 6.0.2 on 2026-02-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analysis', '0002_rename_resume_analysis_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='extra_skill',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='jd_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='matched_skill',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='missing_skill',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='total_matched_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='total_required_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
