SKILL_MAP= {

    "languages": {
        "python": ["python", "python3", "python 3", "py"],
        "java": ["java", "java se", "java ee", "jdk", "jre"],
        "c": ["c", "c language"],
        "cpp": ["c++", "cpp", "c plus plus", "cplusplus"],
        "csharp": ["c#", "c sharp", "c-sharp", "c sharp"],
        "javascript": ["javascript", "js", "java script"],
        "typescript": ["typescript", "ts", "type script"],
        "go": ["go", "golang", "go lang"],
        "rust": ["rust"],
        "php": ["php"],
        "ruby": ["ruby"],
        "swift": ["swift"],
        "kotlin": ["kotlin"],
        "r": ["r", "r language"],
        "sql": ["sql", "structured query language"],
        "bash": ["bash", "shell scripting", "bash shell", "sh", "shell"],
        "powershell": ["powershell", "power shell"],
        "scala": ["scala"],
        "dart": ["dart"],
        "elixir": ["elixir"],
        "erlang": ["erlang"],
        "lua": ["lua"],
        "perl": ["perl"],
        "matlab": ["matlab", "mat lab"],
        "julia": ["julia"],
        "groovy": ["groovy"],
        "objective_c": ["objective-c", "objective c", "objectivec", "obj-c", "objc"],
        "assembly": ["assembly", "asm"],
        "vbnet": ["vb.net", "vb net", "visual basic .net", "visual basic"],
        "vba": ["vba"],
        "solidity": ["solidity", "sol"],
        "haskell": ["haskell"],
        "clojure": ["clojure"],
        "fortran": ["fortran"],
        "cobol": ["cobol"],
    },

    "frontend": {
        "html": ["html"],
        "css": ["css"],
        "react": ["react", "reactjs", "react.js"],
        "nextjs": ["next.js", "nextjs", "next js", "next.js framework"],
        "angular": ["angular", "angularjs", "angular.js"],
        "vue": ["vue", "vuejs", "vue.js", "vue js"],
        "svelte": ["svelte"],
        "redux": ["redux"],
        "bootstrap": ["bootstrap"],
        "tailwind": ["tailwind", "tailwindcss", "tailwind css"],
        "material_ui": ["material ui", "mui", "material-ui"],
        "sass": ["sass", "scss", "sassy css"],
        "less": ["less"],
        "jquery": ["jquery"],
        "alpinejs": ["alpine.js", "alpinejs", "alpine js"],
        "lit": ["lit", "lit-element", "lit element", "lit js"],
        "web_components": ["web components", "webcomponents"],
        "storybook": ["storybook", "story book"],
        "chakra_ui": ["chakra ui", "chakra-ui"],
        "ant_design": ["ant design", "antd", "antdesign"],
        "vite": ["vite"],
        "webpack": ["webpack", "web pack"],
        "rollup": ["rollup"],
        "parcel": ["parcel"],
        "babel": ["babel", "babeljs", "babel js"],
    },

    "backend": {
        "django": ["django"],
        "flask": ["flask"],
        "fastapi": ["fastapi"],
        "spring": ["spring"],
        "spring_boot": ["spring boot", "springboot"],
        "nodejs": ["node.js", "nodejs", "node", "node js"],
        "express": ["express", "expressjs", "express.js"],
        "nestjs": ["nestjs", "nest", "nest.js"],
        "laravel": ["laravel"],
        "aspnet": ["asp.net", "aspnet", "asp net"],
        "rails": ["rails", "ruby on rails", "ror"],
        "graphql": ["graphql", "graph ql", "graph-ql"],
        "rest_api": ["rest api", "restful api", "rest apis", "rest"],
        "microservices": ["microservices", "micro services", "microservice", "micro-service"],
        "fastify": ["fastify"],
        "koa": ["koa"],
        "hapi": ["hapi"],
        "deno": ["deno"],
        "bun": ["bun"],
        "grpc": ["grpc", "g rpc"],
        "websockets": ["websockets", "web sockets", "websocket"],
        "rabbitmq": ["rabbitmq", "rabbit mq", "rabbit-mq"],
        "kafka_streams": ["kafka streams"],
        "spring_cloud": ["spring cloud"],
        "swagger": ["swagger", "swagger api"],
        "openapi": ["openapi", "open api", "open-api"],
    },

    "databases": {
        "mysql": ["mysql"],
        "postgresql": ["postgresql", "postgres", "postgre sql", "postgre"],
        "sqlite": ["sqlite"],
        "mongodb": ["mongodb", "mongo db", "mongo"],
        "redis": ["redis", "redis cache"],
        "oracle": ["oracle"],
        "cassandra": ["cassandra"],
        "dynamodb": ["dynamodb", "dynamo db"],
        "firebase": ["firebase"],
        "neo4j": ["neo4j"],
        "elasticsearch": ["elasticsearch", "elastic search", "elastic"],
        "mariadb": ["mariadb", "maria db", "maria-db"],
        "mssql": ["mssql", "sql server", "microsoft sql server", "ms sql", "ms-sql"],
        "db2": ["db2"],
        "couchdb": ["couchdb", "couch db"],
        "couchbase": ["couchbase"],
        "influxdb": ["influxdb", "influx db"],
        "timescaledb": ["timescaledb", "timescale db"],
        "clickhouse": ["clickhouse", "click house"],
        "bigquery": ["bigquery", "big query"],
        "aurora": ["aurora", "amazon aurora"],
    },

    "cloud": {
        "aws": ["aws", "amazon web services", "amazon aws", "aws cloud"],
        "azure": ["azure", "microsoft azure"],
        "gcp": ["gcp", "google cloud", "google cloud platform", "gcloud"],
        "heroku": ["heroku"],
        "digitalocean": ["digitalocean"],
        "serverless": ["serverless", "serverless framework"],
        "lambda": ["lambda", "aws lambda"],
        "s3": ["s3", "amazon s3"],
        "ec2": ["ec2", "amazon ec2"],
        "rds": ["rds", "amazon rds"],
        "eks": ["eks", "amazon eks"],
        "ecs": ["ecs", "amazon ecs"],
        "ecr": ["ecr", "amazon ecr"],
        "cloudfront": ["cloudfront", "amazon cloudfront"],
        "route53": ["route53", "route 53"],
        "iam": ["iam", "identity and access management"],
        "vpc": ["vpc", "virtual private cloud"],
        "sagemaker": ["sagemaker", "sage maker"],
        "redshift": ["redshift", "amazon redshift"],
        "cloud_run": ["cloud run"],
        "cloud_functions": ["cloud functions", "gcp cloud functions"],
        "pubsub": ["pubsub", "pub sub", "google pubsub"],
        "gke": ["gke", "google kubernetes engine"],
        "cloudflare": ["cloudflare", "cloud flare"],
        "netlify": ["netlify"],
        "vercel": ["vercel"],
        "firebase_hosting": ["firebase hosting"],
    },

    "devops": {
        "docker": ["docker"],
        "kubernetes": ["kubernetes", "k8s"],
        "helm": ["helm"],
        "cicd": ["ci/cd", "ci cd", "ci-cd", "continuous integration", "continuous deployment"],
        "jenkins": ["jenkins"],
        "github_actions": ["github actions"],
        "gitlab_ci": ["gitlab ci", "gitlab ci/cd"],
        "terraform": ["terraform"],
        "ansible": ["ansible"],
        "nginx": ["nginx"],
        "prometheus": ["prometheus"],
        "grafana": ["grafana"],
        "docker_compose": ["docker compose", "docker-compose", "compose"],
        "containerd": ["containerd"],
        "podman": ["podman"],
        "circleci": ["circleci", "circle ci"],
        "travis_ci": ["travis ci"],
        "argo_cd": ["argo cd", "argocd"],
        "flux": ["flux", "fluxcd"],
        "vault": ["vault", "hashicorp vault"],
        "consul": ["consul", "hashicorp consul"],
        "packer": ["packer", "hashicorp packer"],
        "istio": ["istio"],
        "linkerd": ["linkerd"],
    },

    "data_engineering": {
        "hadoop": ["hadoop"],
        "spark": ["spark", "apache spark"],
        "kafka": ["kafka", "apache kafka"],
        "airflow": ["airflow", "apache airflow"],
        "snowflake": ["snowflake"],
        "etl": ["etl", "data extraction", "data transformation", "extract transform load"],
        "data_warehouse": ["data warehouse", "data warehousing", "data warehouseing"],
        "data_pipeline": ["data pipeline", "data pipelines"],
        "flink": ["flink", "apache flink"],
        "beam": ["beam", "apache beam"],
        "dbt": ["dbt", "data build tool", "data build tools"],
        "databricks": ["databricks"],
        "delta_lake": ["delta lake"],
        "lakehouse": ["lakehouse", "data lakehouse"],
        "spark_streaming": ["spark streaming"],
        "kinesis": ["kinesis", "amazon kinesis"],
        "glue": ["glue", "aws glue"],
        "nifi": ["nifi", "apache nifi"],
        "snowplow": ["snowplow"],
        "talend": ["talend"],
        "informatica": ["informatica"],
    },

    "ml_ai": {
        "machine_learning": ["machine learning", "ml"],
        "deep_learning": ["deep learning"],
        "nlp": ["nlp", "natural language processing", "natural-language processing"],
        "computer_vision": ["computer vision"],
        "reinforcement_learning": ["reinforcement learning"],
        "transformers": ["transformers", "transformer"],
        "neural_networks": ["neural network", "neural networks", "nn"],
        "pytorch": ["pytorch", "torch"],
        "tensorflow": ["tensorflow", "tf"],
        "keras": ["keras"],
        "scikit_learn": ["scikit-learn", "sklearn", "scikit learn"],
        "xgboost": ["xgboost"],
        "lightgbm": ["lightgbm"],
        "llm": ["llm", "large language model", "large language models"],
        "generative_ai": ["generative ai", "gen ai", "genai"],
        "catboost": ["catboost"],
        "opencv": ["opencv"],
        "spacy": ["spacy"],
        "nltk": ["nltk"],
        "hugging_face": ["hugging face", "huggingface", "hf"],
        "langchain": ["langchain", "lang chain"],
        "llamaindex": ["llamaindex", "llama index", "llama-index"],
        "onnx": ["onnx"],
        "mlflow": ["mlflow", "ml flow"],
        "ray": ["ray"],
        "kubeflow": ["kubeflow"],
        "prompt_engineering": ["prompt engineering"],
    },

    "data_analysis": {
        "numpy": ["numpy"],
        "pandas": ["pandas"],
        "matplotlib": ["matplotlib"],
        "seaborn": ["seaborn"],
        "tableau": ["tableau"],
        "power_bi": ["power bi", "powerbi", "pbi"],
        "excel": ["excel", "ms excel", "microsoft excel"],
        "statistics": ["statistics", "stats"],
        "ab_testing": ["a/b testing", "ab testing", "a b testing"],
        "scipy": ["scipy"],
        "statsmodels": ["statsmodels"],
        "plotly": ["plotly"],
        "polars": ["polars"],
        "pyspark": ["pyspark"],
        "looker": ["looker"],
        "qlik": ["qlik", "qlikview", "qlik sense", "qlik-view"],
        "superset": ["superset", "apache superset"],
    },

    "security": {
        "cybersecurity": ["cybersecurity", "cyber security", "cyber-sec"],
        "penetration_testing": ["penetration testing", "pentesting", "pen testing", "pen-test"],
        "owasp": ["owasp"],
        "encryption": ["encryption"],
        "network_security": ["network security"],
        "siem": ["siem", "security information and event management"],
        "ethical_hacking": ["ethical hacking"],
        "iam_security": ["iam", "identity and access management"],
        "oauth": ["oauth", "oauth2", "oauth 2.0", "oauth2.0"],
        "jwt": ["jwt", "json web token", "json web tokens"],
        "sso": ["sso", "single sign-on", "single sign on"],
        "mfa": ["mfa", "multi-factor authentication", "multifactor authentication", "2fa"],
        "vulnerability_management": ["vulnerability management"],
        "burp_suite": ["burp suite"],
        "wireshark": ["wireshark"],
        "kali": ["kali", "kali linux","kalilinux"],
        "nmap": ["nmap"],
        "splunk": ["splunk"],
        "tls": ["tls", "transport layer security"],
        "ssl": ["ssl", "secure sockets layer"],
    },

    "testing": {
        "unit_testing": ["unit testing", "unit tests","unit-test", "unittest"],
        "integration_testing": ["integration testing", "integration tests"],
        "pytest": ["pytest"],
        "junit": ["junit", "j unit"],
        "selenium": ["selenium"],
        "cypress": ["cypress", "cypress.io"],
        "test_automation": ["test automation", "automation testing"],
        "jest": ["jest"],
        "mocha": ["mocha"],
        "chai": ["chai"],
        "vitest": ["vitest"],
        "playwright": ["playwright", "playwright testing"],
        "cucumber": ["cucumber"],
        "robot_framework": ["robot framework"],
        "tox": ["tox"],
        "jmeter": ["jmeter", "apache jmeter"],
        "postman_testing": ["postman", "postman testing"],
    },

    "mobile": {
        "android": ["android", "android os"],
        "ios": ["ios", "i os"],
        "react_native": ["react native", "react-native"],
        "flutter": ["flutter"],
        "xamarin": ["xamarin"],
        "swiftui": ["swiftui", "swift ui"],
        "jetpack_compose": ["jetpack compose", "compose"],
        "kotlin_multiplatform": ["kotlin multiplatform", "kmp"],
    },

    "observability": {
        "logging": ["logging", "log management"],
        "monitoring": ["monitoring", "metrics"],
        "tracing": ["tracing", "distributed tracing"],
        "opentelemetry": ["opentelemetry", "open telemetry", "otel"],
        "datadog": ["datadog", "data dog"],
        "new_relic": ["new relic", "newrelic"],
        "elk": ["elk", "elastic stack"],
    },

    "networking": {
        "tcp_ip": ["tcp/ip", "tcp ip"],
        "dns": ["dns", "domain name system"],
        "http": ["http", "https"],
        "load_balancing": ["load balancing", "load-balancing"],
        "cdn": ["cdn", "content delivery network"],
        "vpn": ["vpn", "virtual private network"],
    },

    "operating_systems": {
        "windows": ["windows", "windows os"],
        "macos": ["macos", "mac os", "os x"],
        "linux_os": ["linux", "gnu/linux"],
        "unix": ["unix"],
    },

    "blockchain": {
        "blockchain": ["blockchain", "block chain"],
        "ethereum": ["ethereum", "eth"],
        "smart_contracts": ["smart contracts", "smart contract"],
        "web3": ["web3", "web 3"],
    },

    "game_dev": {
        "unity": ["unity", "unity3d", "unity 3d"],
        "unreal": ["unreal", "unreal engine", "ue"],
        "godot": ["godot"],
    },

    "tools": {
        "git": ["git", "git scm"],
        "github": ["github", "git hub"],
        "gitlab": ["gitlab"],
        "bitbucket": ["bitbucket"],
        "jira": ["jira", "jira software"],
        "linux": ["linux"],
        "postman": ["postman"],
        "figma": ["figma"],
        "vscode": ["vscode", "visual studio code", "vs code"],
        "intellij": ["intellij", "intellij idea"],
        "notion": ["notion"],
        "npm": ["npm"],
        "yarn": ["yarn"],
        "pnpm": ["pnpm"],
        "maven": ["maven"],
        "gradle": ["gradle"],
        "pip": ["pip"],
        "pipenv": ["pipenv"],
        "poetry": ["poetry"],
        "conda": ["conda", "anaconda"],
        "make": ["make", "gnu make"],
        "cmake": ["cmake"],
        "protobuf": ["protobuf", "protocol buffers"],
        "swagger_ui": ["swagger ui"],
        "openapi_tools": ["openapi tools", "openapi generator"],
        "slack": ["slack"],
        "confluence": ["confluence"],
        "trello": ["trello"],
        "dockerhub": ["docker hub", "dockerhub"],
    }
}
